### ISSUE TITLE
Python error 'function' object has no attribute 'list'

### ISSUE THREAD

**Issue by thobus** [elacheche/docker_check#11]
Hello,

calling the python script brings the error:
**'function' object has no attribute 'list'**

Using Python3.
What could be wrong?

**Comment by elacheche** [comment]
Hello @thobus,

Do you only have that as error? There is no "Traceback"? Usually you should get a traceback, if you have that I'd like to get it to know what function is having the issue.

I'd like to try to reproduce that, can you please share the version of:
- Python 3
- Docker
- Docker-py

Also, how do you run your docker containers?

**Comment by thobus** [comment]
Hi elacheche, 

when i call the Python Script only that error comes up. No Traceback.

Versions:
**Python 3.5.2
Docker version 19.03.5, build 633a0ea838
docker_py-1.9.0**

Containers run with the docker daemon, no docker-compose.

**Comment by elacheche** [comment]
How did you got that docker_py package?

YOu need to use this package → https://pypi.org/project/docker/#description

**Comment by thobus** [comment]
I've installed docker with apt-get, not with pip.
Could this be the problem?

**Comment by elacheche** [comment]
It can be.. Depends on where the apt source list is getting that package, and if it's the good package or not..

Please get the python module from:
- pip install docker
- Or https://github.com/docker/docker-py
