### ISSUE TITLE
get_disk_io exception with "index out of range"

### ISSUE THREAD

**Issue by H3rman8** [elacheche/docker_check#2]
While running this script on a docker server i did get an "index out of range" on get_disk_io.
Turns out there is no disk info with some containers (diskless?) so i modified the code locally like below:

    if disk:
      disk_in = disk[0]['value']
      disk_out = disk[1]['value']
    else:
      disk_in = 0
      disk_out = 0

No it runs without issue.

Kind regards,
Herman

**Comment by elacheche** [comment]
Thanks for reporting this..

As I never used a "diskless" docker container.. And I don't know how that can be.. Afaik, each OS process (docker or other) will use disk for I/O at any point of it's life cycle..

Can you please share the output of:
`docker stats <ct_namz>`

To check that there is no disk io data! 

Also, can you please tell me what kind of image is that? If there is a public Dockerfile can you please share it?

I'd like to dig more in this issue..

**Comment by H3rman8** [comment]
Those docker containers are not diskless.
I think its 'docker stats' returning null for zero blkio.

$ docker -v
Docker version 1.13.1-cs3, build 95c9d22

I'm running odoo and ucp (docker datacenter) containers on a centos7 server.

For example docker stats for the odoo container:
CONTAINER                                             CPU %               MEM USAGE / LIMIT      MEM %               NET I/O             BLOCK I/O           PIDS
affectionate_mcclintock.1.t5u0f18m0uwglzrbqb3cxm0ac   0.03%               40.07 MiB / 7.64 GiB   0.51%               1.85 kB / 1.3 kB    0 B / 0 B           4

I'm working on getting performance graph's in nagiosxi to see if those containers ever report disk i/o.
Had issues with nrpe agent v2.x which limits to 1k perfdata. Now using v3.x

**Comment by rnt** [comment]
Hi @elacheche , @hnbakker take a good point.
I have some containers that only read from disk... other only write to disk.

So, in PR #6 , commit 8c8ca32 fix this. ;)

**Comment by elacheche** [comment]
PR #6 is merged, @hnbakker can you please try the new version from the master branch and confirm that the PR fixes the bug.
