### ISSUE TITLE
adding to nagios

### ISSUE THREAD

**Issue by zaraquer** [elacheche/docker_check#3]
Hello Elacheche!

May I ask you how can I add this plugint to nagios?
In icinga2 it works well, but I want to use it in nagios.
Thank you in anticipation!

**Comment by elacheche** [comment]
Hey!

AFAIK, the nagios config should be similar to the Icinga one, take a look at the [config section](https://github.com/elacheche/docker_check#configure-the-monitoring-server) and try to hack it on your Nagios box to get it to work..

If it's very different from the Icinga config, I'll be happy to accept a PR describing the Nagios setup..

**Comment by zaraquer** [comment]
Hi!

This is in my command.cfg

# 'check_docker' command definition
define command{
        command_name    check_docker
        command_line    $USER1$/docker_check.py
        }

And this is on the localgost.cfg which defines the docker server in this case.

define service{
        use                             local-service         ; Name of service template to use
        host_name                       localhost
        service_description             Docker
        check_command                   check_docker
        notifications_enabled           0
        }

And its just pending in the dashboard.

**Comment by elacheche** [comment]
As mentioned in the README file, I am using the "by_ssh" plugin to run the docker plugin.. That means that you need to have a working ssh connection to be able to fetch the plugin output: try to execute the following commands to check if ssh works fine, from your Nagios server:

Switch to the nagios user:
`su - nagios`

Execute the docker_check.py script via SSH:
`ssh $DOCKER-SERVER "/usr/lib/nagios/plugins/docker_check.py"`

This should return output similar to:
`OK | furious_ritchie_mem_pct=0.02% furious_ritchie_cpu_pct=0.0% furious_ritchie_net_in=91137 furious_ritchie_net_out=648 furious_ritchie_disk_in=1003520 furious_ritchie_disk_out=0 elated_booth_mem_pct=1.53% elated_booth_cpu_pct=1.73% elated_booth_net_in=556163 elated_booth_net_out=30239 elated_booth_disk_in=4423680 elated_booth_disk_out=58605568`

If you got the good output then go ahead and try to execute the check via the by_ssh plugin:
`/usr/lib/nagios/plugins/check_by_ssh -H $DOCKER-SERVER -C "/usr/lib/nagios/plugins/docker_check.py" -t 120`

You should get a similar output as the ssh command..

PS: If you're using NRPE than read Nagios docs to find out how to config a new plugin using NRPE, I only using SSH for all my checks.

**Comment by zaraquer** [comment]
After I wrote down my previous post, It gives me the result "ok".
And when I enter in the command, it show me the output what you copied above.
But I still need to investigate how can I configure the limits for the plugin.

**Comment by elacheche** [comment]
You mean % limits for Warning and Critical?

**Comment by elacheche** [comment]
@zaraquer up! :)
