### ISSUE TITLE
Missing keys in container output

### ISSUE THREAD

**Issue by project707** [elacheche/docker_check#7]
It seems like docker is not required to return some keys in the output, so I end up having to hack this script to handle it for the containers that don't. In my case it's specifically that some containers don't have "networks" in the output, so I end up doing something like this:

```
def get_net_io(ct, stats):
    '''Get a container Net In / Out usage since it's launche'''
    if 'networks' in stats[ct]:
        net = stats[ct]['networks']
        net_in = net['eth0']['rx_bytes']
        net_out = net['eth0']['tx_bytes']
    else:
        net_in = 'no data'
        net_out = 'no data'
  
    return [net_in, net_out]
```

Anyhow this could be something weird about our case, I'm honestly not sure.

**Comment by spoer78** [comment]
hi there, thanks for this ... had the same problem. made your changes in my script, but now i get:

> TypeError: get_net_io() missing 1 required positional argument: 'stats'

running this script on a synology nas with dsm 6.1, python3 and pip3 installed...

help would be greatly appreciated.

**Comment by project707** [comment]
Sorry about that @Stinky78. This is the code for that function that I'm running now based on the _current_ version of the script:

```
def get_net_io(stats):
    '''Get a container Net In / Out usage'''
    if 'networks' in stats:
        net_in = stats['networks']['eth0']['rx_bytes']
        net_out = stats['networks']['eth0']['tx_bytes']
    else:
        net_in = 'no data'
        net_out = 'no data'
  
    return net_in, net_out
```

I think I had posted a version of this "fix" that I had made before there were some more recent substantial changes to the script.
