### ISSUE TITLE
Script never return another exit code than 0

### ISSUE THREAD

**Issue by Grimblee** [elacheche/docker_check#8]
Hello,

I have an issue with this script, it never return anything else than 0 as exit code even when something is warn/crit.
Here's a screenshot:
![check_docker_issue](https://user-images.githubusercontent.com/11563475/40918041-77c8059a-6805-11e8-9895-37431e1dadce.png)

Do you have any idea what the issue could be ?
Python is in version 2.7.5

Thank you,

**Comment by elacheche** [comment]
Hello,

Are you using the latest version from the repo?

You can't be using Python2.7.5 to run the script, the usage of [Python3 is hard coded in it](https://github.com/elacheche/docker_check/blob/06051c977484985ecbaad0874820f8d2f66dd631/docker_check.py#L1)

**Comment by Grimblee** [comment]
Indeed, here's python3's version:
> root@vl2413itrpaccweb1 icinga2 # python3 --version
> Python 3.4.5

And I have just updated the repo and copied the script again to the machine in question:
> root@vl2413itrpaccweb1 icinga2 # ./docker_check.py; echo $?
> WARNING: itrp_rails_1_mem_pct have 72.11% | itrp_rails_1_disk_in=82706432 itrp_rails_1_disk_out=0 itrp_rails_1_mem_pct=72.11 itrp_rails_1_cpu_pct=1.1375587 itrp_rails_1_net_out=10483879858 itrp_rails_1_net_in=27561525703
> 0

**Comment by elacheche** [comment]
@Grimblee I made some tests, the latest commit should fix the issue.

The exceptions where trying to handle the sys.exit calls, but those make the script exit code equal to 0 as it override the sys.exit value from the test.

Fell free to reopen this issue if you find that problem is not solved yet.

**Comment by Grimblee** [comment]
It now works:
> root@vl2413itrpaccweb1 icinga2 # ./docker_check.py; echo $?
> WARNING: itrp_rails_1_mem_pct have 72.02% | itrp_rails_1_net_out=10507346978 itrp_rails_1_disk_out=0 itrp_rails_1_cpu_pct=0.8870227135678391 itrp_rails_1_net_in=27580614227 itrp_rails_1_disk_in=82812928 itrp_rails_1_mem_pct=72.02
> 1

Thank you for your help and for your nice script :)

**Comment by elacheche** [comment]
Happy to be able to help :)

Thanks for using it! It makes me feel happy to know that someone find this useful and uses it! :)
