### ISSUE TITLE
License

### ISSUE THREAD

**Issue by elacheche** [elacheche/docker_check#9]
Hello,

@rnt and @yulius-fxpal I'd like to have a chitchat with you about the project license.

For some weird reason, I totally forgot about adding a License when I started the project, I never thought that someone will contribute to it any time soon.

When you contributed to it, it's not my project anymore, your code is there, we share ownership of it, so I need your permission/input to add a License to the plugin.

I would to add a [GPL-Compatible Free Software Licenses](https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses) to the project.

Can you please help with inputs about this?

**Comment by yulius-fxpal** [comment]
Yes.  Please add the GPL license.

**Comment by elacheche** [comment]
Hey! Thanks for the input @yulius-fxpal,  I was re-reading the script thinking that I should do some refactoring, I figured out that I mentioned the license just after the imports section from the beginning.

I'll add a License.md to the project so that can be clear.

**Comment by rnt** [comment]
Go for it! <3
